import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className="header__left">
          <img className="header__img" src="logo.png" alt="" />
          <h3 className="headar__name">CryptoHype</h3>
        </div>
        <nav>
          <ul className="header__items">
            <li className="header__item">Market</li>
            <li className="header__item">Disover</li>
            <li className="header__item">About</li>
            <li className="header__item">Artist</li>
          </ul>
        </nav>

        <div className="header__search-bar">
          <input
            placeholder="Search related to NFT"
            type="search"
            name="q"
          />
        </div>
      </header>

      <main>
        <content className="main-left">
          <ul className="main-left-items">
            <li className="main-left-item">
              Best <span className="left-gradian">NFT</span>
            </li>
            <li className="main-left-item">Collection for</li>
            <li className="main-left-item">Your Future</li>
          </ul>
          <div className="left-btn">
            <button className="btn-explore">Explore Now</button>
            <button className="btn-create">Create NFT</button>
          </div>
        </content>

        <content className="main-right">
          <div className="main-rond-right">
            <img className="personnage" src="elephant.png" alt="" />!{' '}
          </div>
        </content>
      </main>
    </div>
  );
}
