import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div classNameName={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>

        <div className="left-logo">
            {/* <img className="logo" src="./apple.jpg" alt=""> */}
            <h3 className="nav-name">CryptoHype</h3>
        </div>
        <nav>
            <ul className="nav-items">
                <li className="nav-item">Market</li>
                <li className="nav-item">Disover</li>
                <li className="nav-item">About</li>
                <li className="nav-item">Artist</li>
            </ul>
        

        </nav>
        
        
        <input className="header-input" placeholder="Search related to NFT" type="search" id="site-search" name="q" />
              

</header>

<main>
    <content className="main-left">
        <ul className="main-left-items">
            <li className="main-left-item">Best <span className="left-gradian">NFT</span></li>
            <li className="main-left-item">Collection for</li>
            <li className="main-left-item">Your Future</li>
        </ul>
        <div className="left-btn">
            <button className="btn-explore">Explore Now</button>
            <button className="btn-create">Create NFT</button>
        </div>
    </content>


    <content className="main-right">

        <div className="main-rond-right">
!        </div>
        
    </content>
</main>



      

   
    </div>
  )
}
